
package com.ups.wsdl.xoltws.freightrate.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import com.ups.xmlschema.xoltws.freightrate.v1.FreightRateRequest;
import com.ups.xmlschema.xoltws.freightrate.v1.FreightRateResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebService(name = "FreightRatePortType", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightRate/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FreightRatePortType {


    /**
     * 
     * @param body
     * @param upsSecurity
     * @return
     *     returns com.ups.xmlschema.xoltws.freightrate.v1.FreightRateResponse
     * @throws RateErrorMessage
     */
    @WebMethod(operationName = "ProcessFreightRate", action = "http://onlinetools.ups.com/webservices/FreightRateBinding/v1.0")
    @WebResult(name = "FreightRateResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightRate/v1.0", partName = "Body")
    public FreightRateResponse processFreightRate(
        @WebParam(name = "FreightRateRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightRate/v1.0", partName = "Body")
        FreightRateRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws RateErrorMessage
    ;

}
