
package com.ups.wsdl.xoltws.freightrate.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "FreightRateService", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightRate/v1.0", wsdlLocation = "file:/Users/vishsahu/Downloads/Rates_Pkg_Gnd/RatingGROUNDFREIGHTWebService/SCHEMA-WSDLs/FreightRate.wsdl")
public class FreightRateService
    extends Service
{

    private final static URL FREIGHTRATESERVICE_WSDL_LOCATION;
    private final static WebServiceException FREIGHTRATESERVICE_EXCEPTION;
    private final static QName FREIGHTRATESERVICE_QNAME = new QName("http://www.ups.com/WSDL/XOLTWS/FreightRate/v1.0", "FreightRateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/vishsahu/Downloads/Rates_Pkg_Gnd/RatingGROUNDFREIGHTWebService/SCHEMA-WSDLs/FreightRate.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FREIGHTRATESERVICE_WSDL_LOCATION = url;
        FREIGHTRATESERVICE_EXCEPTION = e;
    }

    public FreightRateService() {
        super(__getWsdlLocation(), FREIGHTRATESERVICE_QNAME);
    }

    public FreightRateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns FreightRatePortType
     */
    @WebEndpoint(name = "FreightRatePort")
    public FreightRatePortType getFreightRatePort() {
        return super.getPort(new QName("http://www.ups.com/WSDL/XOLTWS/FreightRate/v1.0", "FreightRatePort"), FreightRatePortType.class);
    }

    private static URL __getWsdlLocation() {
        if (FREIGHTRATESERVICE_EXCEPTION!= null) {
            throw FREIGHTRATESERVICE_EXCEPTION;
        }
        return FREIGHTRATESERVICE_WSDL_LOCATION;
    }

}
